project_id = "kqlytfyvlosnhbszkesd"

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.generate-lesson-audio]
verify_jwt = false

[functions.upload-lesson-audio]
verify_jwt = false
