project_id = "kqlytfyvlosnhbszkesd"

[functions.generate-lesson-audio]
verify_jwt = false

[functions.upload-lesson-audio]
verify_jwt = false

[functions.delete-lesson-audio]
verify_jwt = false

[functions.delete-account]
verify_jwt = false
